server:
  port: 8181
  servlet:
    context-path: /tech-bazzar-auth

spring:
  flyway:
    baselineOnMigrate: true
    url: jdbc:postgresql://localhost:5432/tech_bazzar_auth
    user: ${db_username}
    password: ${db_password}
    validateOnMigrate: false

  datasource:
    url: jdbc:postgresql://localhost:5432/tech_bazzar_auth
    driverClassName: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}

  mail:
    protocol: smtps
    host: smtp.mail.ru
    port: 465
    username: ${email_username}
    password: ${email_password}

  jpa:
    showSql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddlAuto: update

jwt:
  secret: ${jwt_secret}
  lifetime: 36_000_000_000