server:
  port: 8555
  servlet:
    context-path: /tech-bazzar-picture

spring:
  servlet:
    multipart:
      max-file-size: 5MB

  datasource:
    url: jdbc:postgresql://postgres-picture-service:5436/picture_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  flyway:
    baselineOnMigrate: true
    url: jdbc:postgresql://postgres-picture-service:5436/picture_db
    user: postgres
    password: admin
    validateOnMigrate: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka

integrations:
  auth-service:
    url: http://user-service:8181/tech-bazzar-user/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  cart-service:
    url: http://cart-service:8182/tech-bazzar-cart/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  organization-service:
    url: http://organization-service:8185/tech-bazzar-organization/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  core-service:
    url: http://core-service:8183/tech-bazzar-core/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

springdoc:
  swagger-ui:
    supported-submit-methods: "get"
