server:
  port: 8182
  servlet:
    context-path: /tech-bazzar-cart

integrations:
  product-service:
    url: http://localhost:8183/tech-bazzar-core/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

cart-service:
  cart-prefix: tech_cart_